import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { get, set } from 'idb-keyval';
import { supabase } from '../lib/supabase';

interface PendingAction {
  id: string; // Unique ID for the action itself
  type: 'CREATE_PURCHASE' | 'CREATE_FARMER' | 'CREATE_ADVANCE' | 'UPDATE_ADVANCE' | 'UPDATE_FARMER' | 'CREATE_PURCHASE_ATOMIC'; // Extendable
  payload: any;
  timestamp: number;
}

interface SyncContextType {
  isOnline: boolean;
  pendingSyncCount: number;
  addToSyncQueue: (type: PendingAction['type'], payload: any) => Promise<void>;
  forceSync: () => Promise<void>;
  isSyncing: boolean;
}

const SyncContext = createContext<SyncContextType | undefined>(undefined);

const QUEUE_KEY = 'offline_sync_queue';

export function SyncProvider({ children }: { children: React.ReactNode }) {
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [pendingSyncCount, setPendingSyncCount] = useState(0);
  const [isSyncing, setIsSyncing] = useState(false);

  // Load initial queue count
  const refreshQueueCount = useCallback(async () => {
    try {
      const queue: PendingAction[] = await get(QUEUE_KEY) || [];
      setPendingSyncCount(queue.length);
    } catch (e) {
      console.error('Failed to read sync queue count', e);
    }
  }, []);

  const addToSyncQueue = async (type: PendingAction['type'], payload: any) => {
    try {
      const queue: PendingAction[] = await get(QUEUE_KEY) || [];
      const newAction: PendingAction = {
        id: crypto.randomUUID(),
        type,
        payload,
        timestamp: Date.now()
      };
      await set(QUEUE_KEY, [...queue, newAction]);
      await refreshQueueCount();
      
      // If we are actually online, try syncing immediately
      if (isOnline) {
        processQueue();
      }
    } catch (e) {
      console.error('Failed to add to sync queue', e);
    }
  };

  const processSingleAction = async (action: PendingAction) => {
    switch (action.type) {
      case 'CREATE_PURCHASE_ATOMIC':
        const { error: rpcError } = await supabase.rpc('record_purchase_v1', action.payload);
        if (rpcError) throw rpcError;
        break;
      case 'CREATE_PURCHASE':
        // Specifically avoid the id generation on the server if we already have it in the payload.
        // We will assert the payload has already been optimistically generated by the local client.
        const { error: pError } = await supabase
          .from('purchases')
          .insert(action.payload);
        if (pError) throw pError;
        break;
      case 'CREATE_FARMER':
        const { error: fError } = await supabase.from('farmers').insert(action.payload);
        if (fError) throw fError;
        break;
      case 'UPDATE_ADVANCE':
        const { id, ...updateData } = action.payload;
        const { error: aError } = await supabase.from('advances').update(updateData).eq('id', id);
        if (aError) throw aError;
        break;
      case 'UPDATE_FARMER':
        const { id: fId, ...fUpdateData } = action.payload;
        const { error: ufError } = await supabase.from('farmers').update(fUpdateData).eq('id', fId);
        if (ufError) throw ufError;
        break;
      default:
        console.warn('Unknown sync action type:', action.type);
    }
  };

  const processQueue = useCallback(async () => {
    if (isSyncing || !isOnline) return;

    try {
      setIsSyncing(true);
      let queue: PendingAction[] = await get(QUEUE_KEY) || [];
      
      if (queue.length === 0) {
        setIsSyncing(false);
        return;
      }

      // Sort by oldest first to maintain sequential integrity
      queue.sort((a, b) => a.timestamp - b.timestamp);

      const remainingQueue = [...queue];

      for (const action of queue) {
        try {
          await processSingleAction(action);
          // Only remove if it succeeded
          remainingQueue.shift();
          await set(QUEUE_KEY, remainingQueue);
          setPendingSyncCount(remainingQueue.length);
        } catch (error) {
          console.error(`Failed to sync action ${action.id}:`, error);
          // Stop processing the queue if an error occurs to maintain order 
          // (e.g., if internet drops halfway through, or a FK constraint fails, we should handle it gracefully)
          break; 
        }
      }
    } catch (e) {
      console.error('Error during sync process:', e);
    } finally {
      setIsSyncing(false);
    }
  }, [isOnline, isSyncing]);

  useEffect(() => {
    refreshQueueCount();

    const handleOnline = () => {
      setIsOnline(true);
      processQueue(); // Automatically trigger sync
    };
    
    const handleOffline = () => {
      setIsOnline(false);
    };

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    // Initial check just in case we started online with things in queue
    if (navigator.onLine) {
      processQueue();
    }

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [processQueue, refreshQueueCount]);

  return (
    <SyncContext.Provider value={{ isOnline, pendingSyncCount, addToSyncQueue, forceSync: processQueue, isSyncing }}>
      {children}
    </SyncContext.Provider>
  );
}

export function useSync() {
  const context = useContext(SyncContext);
  if (context === undefined) {
    throw new Error('useSync must be used within a SyncProvider');
  }
  return context;
}
