import React, { createContext, useContext, useState, useEffect, useCallback, useRef } from 'react';
import { get, set } from 'idb-keyval';
import { supabase } from '../lib/supabase';

interface PendingAction {
  id: string; 
  type: 
    | 'CREATE_PURCHASE' 
    | 'CREATE_FARMER' 
    | 'CREATE_ADVANCE' 
    | 'UPDATE_ADVANCE' 
    | 'UPDATE_FARMER' 
    | 'CREATE_PURCHASE_ATOMIC'
    | 'CREATE_PRICE'
    | 'CREATE_EXPENSE'
    | 'CREATE_SALE'
    | 'UPDATE_SEASON'
    | 'CREATE_SEASON'
    | 'DELETE_ITEM'
    | 'CREATE_FARMER_PAYMENT';
  payload: any;
  timestamp: number;
}

interface SyncContextType {
  isOnline: boolean;
  pendingSyncCount: number;
  addToSyncQueue: (type: PendingAction['type'], payload: any) => Promise<void>;
  forceSync: () => Promise<void>;
  isSyncing: boolean;
}

const SyncContext = createContext<SyncContextType | undefined>(undefined);

const QUEUE_KEY = 'offline_sync_queue';

export function SyncProvider({ children }: { children: React.ReactNode }) {
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [pendingSyncCount, setPendingSyncCount] = useState(0);
  const [isSyncing, setIsSyncing] = useState(false);
  // Use a ref to guard against concurrent runs without causing re-renders
  // that would recreate processQueue and trigger an infinite useEffect loop.
  const isSyncingRef = useRef(false);

  // Load initial queue count
  const refreshQueueCount = useCallback(async () => {
    try {
      const queue: PendingAction[] = await get(QUEUE_KEY) || [];
      setPendingSyncCount(queue.length);
    } catch (e) {
      console.error('Failed to read sync queue count', e);
    }
  }, []);

  const addToSyncQueue = async (type: PendingAction['type'], payload: any) => {
    try {
      const queue: PendingAction[] = await get(QUEUE_KEY) || [];
      const newAction: PendingAction = {
        id: crypto.randomUUID(),
        type,
        payload,
        timestamp: Date.now()
      };
      await set(QUEUE_KEY, [...queue, newAction]);
      await refreshQueueCount();
      
      // If we are actually online, try syncing immediately
      if (isOnline) {
        processQueue();
      }
    } catch (e) {
      console.error('Failed to add to sync queue', e);
    }
  };

  const processSingleAction = async (action: PendingAction) => {
    switch (action.type) {
      case 'CREATE_PURCHASE_ATOMIC':
        const { error: rpcError } = await supabase.rpc('record_purchase_v1', action.payload);
        if (rpcError) throw rpcError;
        break;
      case 'CREATE_PURCHASE':
        // Specifically avoid the id generation on the server if we already have it in the payload.
        // We will assert the payload has already been optimistically generated by the local client.
        const { error: pError } = await supabase
          .from('purchases')
          .insert(action.payload);
        if (pError) throw pError;
        break;
      case 'CREATE_FARMER':
        const { error: fError } = await supabase.from('farmers').insert(action.payload);
        if (fError) throw fError;
        break;
      case 'CREATE_ADVANCE':
        const { error: advError } = await supabase.from('advances').insert(action.payload);
        if (advError) throw advError;
        break;
      case 'CREATE_PRICE':
        const { error: priceError } = await supabase.from('buying_prices').insert(action.payload);
        if (priceError) throw priceError;
        break;
      case 'CREATE_EXPENSE':
        const { error: expError } = await supabase.from('expenses').insert(action.payload);
        if (expError) throw expError;
        break;
      case 'CREATE_SALE':
        const { error: saleError } = await supabase.from('sales').insert(action.payload);
        if (saleError) throw saleError;
        break;
      case 'CREATE_SEASON':
        const { error: sError } = await supabase.from('seasons').insert(action.payload);
        if (sError) throw sError;
        break;
      case 'UPDATE_SEASON':
        const { id: sId, ...sUpdateData } = action.payload;
        const { error: usError } = await supabase.from('seasons').update(sUpdateData).eq('id', sId);
        if (usError) throw usError;
        break;
      case 'CREATE_FARMER_PAYMENT':
        const { error: fpError } = await supabase.from('farmer_payments').insert(action.payload);
        if (fpError) throw fpError;
        break;
      case 'DELETE_ITEM':
        const { table, id: delId } = action.payload;
        const { error: delError } = await supabase.from(table).delete().eq('id', delId);
        if (delError) throw delError;
        break;
      case 'UPDATE_ADVANCE':
        const { id, ...updateData } = action.payload;
        const { error: aError } = await supabase.from('advances').update(updateData).eq('id', id);
        if (aError) throw aError;
        break;
      case 'UPDATE_FARMER':
        const { id: fId, ...fUpdateData } = action.payload;
        const { error: ufError } = await supabase.from('farmers').update(fUpdateData).eq('id', fId);
        if (ufError) throw ufError;
        break;
      default:
        console.warn('Unknown sync action type:', action.type);
    }
  };

  const processQueue = useCallback(async () => {
    // Use ref instead of state to avoid recreating this callback on every sync
    // which would cause an infinite useEffect re-run loop
    if (isSyncingRef.current || !isOnline) return;

    try {
      isSyncingRef.current = true;
      setIsSyncing(true);
      let queue: PendingAction[] = await get(QUEUE_KEY) || [];
      
      if (queue.length === 0) {
        return;
      }

      // Sort by oldest first to maintain sequential integrity
      queue.sort((a, b) => a.timestamp - b.timestamp);

      const remainingQueue = [...queue];

      for (const action of queue) {
        try {
          await processSingleAction(action);
          // Only remove if it succeeded
          remainingQueue.shift();
          await set(QUEUE_KEY, remainingQueue);
          setPendingSyncCount(remainingQueue.length);
        } catch (error) {
          console.error(`Failed to sync action ${action.id}:`, error);
          // Stop processing the queue if an error occurs to maintain order 
          // (e.g., if internet drops halfway through, or a FK constraint fails, we should handle it gracefully)
          break; 
        }
      }
    } catch (e) {
      console.error('Error during sync process:', e);
    } finally {
      isSyncingRef.current = false;
      setIsSyncing(false);
    }
  }, [isOnline]); // Removed isSyncing — now guarded by isSyncingRef to prevent infinite loop

  useEffect(() => {
    refreshQueueCount();

    const handleOnline = () => {
      setIsOnline(true);
      processQueue(); // Automatically trigger sync
    };
    
    const handleOffline = () => {
      setIsOnline(false);
    };

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    // Initial check just in case we started online with things in queue
    if (navigator.onLine) {
      processQueue();
    }

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [processQueue, refreshQueueCount]);

  return (
    <SyncContext.Provider value={{ isOnline, pendingSyncCount, addToSyncQueue, forceSync: processQueue, isSyncing }}>
      {children}
    </SyncContext.Provider>
  );
}

export function useSync() {
  const context = useContext(SyncContext);
  if (context === undefined) {
    throw new Error('useSync must be used within a SyncProvider');
  }
  return context;
}
